
spring:
  application:
    name: sleuth-rabbit
  main:
    banner-mode: "off"
  cloud:
    stream:
      bindings:
        supplyMessages-out-0:
          destination: topic
        receiveMessages-in-0:
          destination: topic
          group: queue
    function:
      definition: supplyMessages;receiveMessages

spring.zipkin:
  baseUrl: http://localhost:9411/
  sender.type: web


